services:
  auth-middleware:
    container_name: skyfall-auth-middleware
    build: .
    image: ricardobgx/skyfall-auth-middleware
    environment:
      - SKYFALL_AUTH_MIDDLEWARE_HTTP_PORT=${SKYFALL_AUTH_MIDDLEWARE_HTTP_PORT}
      - SKYFALL_TASKS_API_URL=${SKYFALL_TASKS_API_URL}
      - SKYFALL_AUTH_MIDDLEWARE_OAUTH2_JWK_SET_URL=${SKYFALL_AUTH_MIDDLEWARE_OAUTH2_JWK_SET_URL}
      - SKYFALL_AUTH_MIDDLEWARE_OAUTH2_JWT_ISSUER_URL=${SKYFALL_AUTH_MIDDLEWARE_OAUTH2_JWT_ISSUER_URL}
      - SKYFALL_AUTH_MIDDLEWARE_OPENID_CLIENT_ID=${SKYFALL_AUTH_MIDDLEWARE_OPENID_CLIENT_ID}
      - SKYFALL_AUTH_MIDDLEWARE_OPENID_CLIENT_SECRET=${SKYFALL_AUTH_MIDDLEWARE_OPENID_CLIENT_SECRET}
    ports:
      - '${SKYFALL_AUTH_MIDDLEWARE_HTTP_PORT}:${SKYFALL_AUTH_MIDDLEWARE_HTTP_PORT}'
    networks:
      - skyfall-network
    restart: always
