server:
  port: ${SKYFALL_AUTH_MIDDLEWARE_HTTP_PORT}

spring:
  application:
    name: auth-middleware
  cloud:
    gateway:
      routes:
        - id: tasks-api
          uri: ${SKYFALL_TASKS_API_URL}
          predicates:
            - Path=/api/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - TokenRelay=
            - SaveSession
            - StripPrefix=1
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${SKYFALL_AUTH_MIDDLEWARE_OAUTH2_JWK_SET_URL}
      client:
        provider:
          keycloak:
            issuer-uri: ${SKYFALL_AUTH_MIDDLEWARE_OAUTH2_JWT_ISSUER_URL}
        registration:
          keycloak:
            provider: keycloak
            authorization-grant-type: authorization_code
            client-id: ${SKYFALL_AUTH_MIDDLEWARE_OPENID_CLIENT_ID}
            client-secret: ${SKYFALL_AUTH_MIDDLEWARE_OPENID_CLIENT_SECRET}
            scope: openid,profile,email,offline_access